# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
# prettier-ignore
{{ if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lfx-v2-mentorship-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-v2-mentorship-service.labels" . | nindent 4 }}
  annotations: {{- .Values.serviceAccount.annotations | default (dict) | toYaml | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
# prettier-ignore
{{ end }}
