// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import type { AdminProgramDetail } from '../../app/types/admin.types';

export const MOCK_ADMIN_PROGRAM_DETAILS: Record<string, AdminProgramDetail> = {
  'ap-1': {
    id: 'ap-1',
    name: 'GridFlow: Time-Series Ingestion Pipeline',
    foundationName: 'LF Energy',
    termLabel: 'Term 3 - 2026',
    status: 'published',
    stats: {
      mentors: 4,
      currentMentees: 6,
      graduatedMentees: 18,
      fundingToDateCents: 900_000,
    },
    description:
      'Build a reliable time-series ingestion pipeline for grid operators. Mentees work on streaming ingestion, schema design, and operator-facing observability.',
    skills: ['Python', 'Rust', 'Kafka', 'Git'],
    repositoryUrl: 'https://github.com/lfenergy/gridflow',
    websiteUrl: 'https://www.lfenergy.org/',
    about:
      'GridFlow mentors guide mentees through production-grade energy data pipelines with weekly reviews and clear contribution milestones.',
    termDetailsLabel: 'Term 3 · Sep-Nov 2026',
    applicationsCloseLabel: 'Jul 15, 2026',
    currentMentees: [
      {
        id: 'am-1',
        name: 'Ifeoma Adeyemi',
        termLabel: 'Term 3 · 2026',
        status: 'pending',
        createdLabel: 'Jun 28, 2026',
        updatedLabel: 'Jul 2, 2026',
        otherApplications: [{ programName: 'Apicurio Registry', status: 'pending' }],
      },
      {
        id: 'am-2',
        name: 'Diego Souza',
        termLabel: 'Term 3 · 2026',
        status: 'accepted',
        createdLabel: 'Jun 12, 2026',
        updatedLabel: 'Jun 30, 2026',
        otherApplications: [],
      },
      {
        id: 'am-3',
        name: 'Maya Patel',
        termLabel: 'Term 3 · 2026',
        status: 'tasks-submitted',
        createdLabel: 'May 20, 2026',
        updatedLabel: 'Jul 1, 2026',
        otherApplications: [{ programName: 'Kubernetes Contributors', status: 'pending' }],
      },
    ],
    pastMentees: [
      {
        id: 'am-p1',
        name: 'Grace Wanjiru',
        termLabel: 'Term 2 · 2026',
        status: 'graduated',
        createdLabel: 'Jan 10, 2026',
        updatedLabel: 'Apr 20, 2026',
        otherApplications: [],
      },
      {
        id: 'am-p2',
        name: 'Ravi Menon',
        termLabel: 'Term 2 · 2026',
        status: 'declined',
        createdLabel: 'Jan 14, 2026',
        updatedLabel: 'Feb 2, 2026',
        otherApplications: [],
      },
      {
        id: 'am-p3',
        name: 'Ines Duarte',
        termLabel: 'Term 1 · 2026',
        status: 'graduated',
        createdLabel: 'Sep 5, 2025',
        updatedLabel: 'Dec 1, 2025',
        otherApplications: [],
      },
      {
        id: 'am-p4',
        name: 'Omar Hassan',
        termLabel: 'Term 1 · 2026',
        status: 'withdrawn',
        createdLabel: 'Sep 12, 2025',
        updatedLabel: 'Oct 3, 2025',
        otherApplications: [],
      },
      {
        id: 'am-p5',
        name: 'Hana Suzuki',
        termLabel: 'Term 2 · 2026',
        status: 'graduated',
        createdLabel: 'Jan 8, 2026',
        updatedLabel: 'Apr 18, 2026',
        otherApplications: [],
      },
    ],
    mentors: [
      {
        id: 'amo-1',
        name: 'Dana Okafor',
        status: 'approved',
        entryLabel: 'Invited Apr 2, 2026',
        profileCreated: true,
      },
      {
        id: 'amo-2',
        name: 'Amina Reyes',
        status: 'approved',
        entryLabel: 'Applied May 18, 2026',
        profileCreated: true,
      },
      {
        id: 'amo-3',
        name: 'Chris Okonkwo',
        status: 'pending',
        entryLabel: 'Invited Jun 1, 2026',
        profileCreated: false,
      },
      {
        id: 'amo-4',
        name: 'Priya Shah',
        status: 'approved',
        entryLabel: 'Applied Mar 22, 2026',
        profileCreated: true,
      },
    ],
    managedTerms: [
      {
        id: 'at-3',
        name: 'Term 3 · 2026',
        status: 'open',
        pending: 3,
        declined: 1,
        accepted: 2,
        graduated: 0,
        startLabel: 'Sep 2026',
        endLabel: 'Nov 2026',
        applicationStartLabel: 'May 1, 2026',
        applicationEndLabel: 'Jul 15, 2026',
      },
      {
        id: 'at-2',
        name: 'Term 2 · 2026',
        status: 'closed',
        pending: 0,
        declined: 2,
        accepted: 4,
        graduated: 3,
        startLabel: 'Apr 2026',
        endLabel: 'Jun 2026',
        applicationStartLabel: 'Jan 5, 2026',
        applicationEndLabel: 'Mar 1, 2026',
      },
      {
        id: 'at-1',
        name: 'Term 1 · 2026',
        status: 'closed',
        pending: 0,
        declined: 1,
        accepted: 5,
        graduated: 4,
        startLabel: 'Jan 2026',
        endLabel: 'Mar 2026',
        applicationStartLabel: 'Oct 1, 2025',
        applicationEndLabel: 'Dec 15, 2025',
      },
    ],
  },
  'ap-2': {
    id: 'ap-2',
    name: 'Apicurio Registry: Prompt Template Playground',
    foundationName: 'CNCF',
    termLabel: 'Term 3 - 2026',
    status: 'published',
    stats: {
      mentors: 2,
      currentMentees: 4,
      graduatedMentees: 12,
      fundingToDateCents: 1_200_000,
    },
    description:
      'Extend Apicurio Registry with a prompt-template playground for cloud-native API artifact management.',
    skills: ['Java', 'TypeScript', 'OpenAPI', 'Git'],
    repositoryUrl: 'https://github.com/Apicurio/apicurio-registry',
    about: 'Help API teams prototype and share prompt templates safely.',
    termDetailsLabel: 'Term 3 · Sep-Nov 2026',
    applicationsCloseLabel: 'Jul 10, 2026',
    currentMentees: [
      {
        id: 'am-4',
        name: 'Noah Berg',
        termLabel: 'Term 3 · 2026',
        status: 'pending',
        createdLabel: 'Jun 20, 2026',
        updatedLabel: 'Jun 22, 2026',
        otherApplications: [],
      },
    ],
    pastMentees: [
      {
        id: 'am-p6',
        name: 'Casey Ng',
        termLabel: 'Term 2 · 2026',
        status: 'graduated',
        createdLabel: 'Jan 3, 2026',
        updatedLabel: 'Apr 12, 2026',
        otherApplications: [],
      },
    ],
    mentors: [
      {
        id: 'amo-5',
        name: 'Avery Kim',
        status: 'approved',
        entryLabel: 'Invited Feb 10, 2026',
        profileCreated: true,
      },
      {
        id: 'amo-6',
        name: 'Sam Chen',
        status: 'pending',
        entryLabel: 'Applied Jun 4, 2026',
        profileCreated: false,
      },
    ],
    managedTerms: [
      {
        id: 'at-a3',
        name: 'Term 3 · 2026',
        status: 'open',
        pending: 1,
        declined: 0,
        accepted: 1,
        graduated: 0,
        startLabel: 'Sep 2026',
        endLabel: 'Nov 2026',
        applicationStartLabel: 'May 1, 2026',
        applicationEndLabel: 'Jul 10, 2026',
      },
    ],
  },
  'ap-3': {
    id: 'ap-3',
    name: 'Kubernetes Contributors',
    foundationName: 'CNCF',
    termLabel: 'Term 2 - 2026',
    status: 'pending-review',
    stats: {
      mentors: 3,
      currentMentees: 0,
      graduatedMentees: 9,
      fundingToDateCents: 0,
    },
    description:
      'A mentorship track helping new contributors learn Kubernetes contribution workflows, SIGs, and community practices.',
    skills: ['Go', 'Kubernetes', 'Git', 'CI/CD'],
    repositoryUrl: 'https://github.com/kubernetes/community',
    about: 'Work with Kubernetes mentors to make your first meaningful contributions.',
    termDetailsLabel: 'Term 2 · Apr-Jun 2026',
    applicationsCloseLabel: 'Feb 28, 2026',
    currentMentees: [],
    pastMentees: [
      {
        id: 'am-p7',
        name: 'Alex Rivera',
        termLabel: 'Term 1 · 2026',
        status: 'graduated',
        createdLabel: 'Sep 1, 2025',
        updatedLabel: 'Dec 10, 2025',
        otherApplications: [],
      },
    ],
    mentors: [
      {
        id: 'amo-7',
        name: 'Priya Shah',
        status: 'approved',
        entryLabel: 'Invited Jan 8, 2026',
        profileCreated: true,
      },
    ],
    managedTerms: [
      {
        id: 'at-k2',
        name: 'Term 2 · 2026',
        status: 'closed',
        pending: 0,
        declined: 0,
        accepted: 0,
        graduated: 1,
        startLabel: 'Apr 2026',
        endLabel: 'Jun 2026',
        applicationStartLabel: 'Jan 5, 2026',
        applicationEndLabel: 'Feb 28, 2026',
      },
    ],
  },
};

export function getAdminProgramDetail(id: string): AdminProgramDetail | undefined {
  return MOCK_ADMIN_PROGRAM_DETAILS[id];
}
