# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lfx-mentorship-frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-mentorship-frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
