# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: lfx-mentorship-frontend
description: LFX Mentorship Nuxt 4 Frontend BFF
type: application
# This version is a placeholder — it is overridden with the release tag by ci-release.yml at publish time.
version: 0.0.1
appVersion: "latest"
keywords:
  - lfx
  - mentorship
  - frontend
home: https://github.com/linuxfoundation/lfx-mentorship
sources:
  - https://github.com/linuxfoundation/lfx-mentorship
maintainers:
  - name: LFX Engineering
    email: lfx-engineering@linuxfoundation.org
